import sqlite3, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
conn = sqlite3.connect(r'C:\Users\Matt\.job-hunter-mcp\jobs.db')
c = conn.cursor()
c.execute("UPDATE jobs SET status='applied', applied_date='2026-03-19' WHERE title LIKE '%Middleware%' AND company LIKE '%WinCo%'")
print(f'Updated {c.rowcount} rows for WinCo')
c.execute("SELECT COUNT(*) FROM jobs WHERE status='applied'")
print(f'Total applied: {c.fetchone()[0]}')
conn.commit()
conn.close()
