import sys, sqlite3
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
db = sqlite3.connect(r'C:\Users\Matt\.job-hunter-mcp\jobs.db', timeout=30)
c = db.cursor()
c.execute('SELECT COUNT(*) FROM jobs')
print(f"Total: {c.fetchone()[0]}")
c.execute("SELECT COUNT(*) FROM jobs WHERE fit_score <= 1 AND status='new'")
print(f"New unscored: {c.fetchone()[0]}")
c.execute("SELECT COUNT(*) FROM jobs WHERE status='applied'")
print(f"Applied: {c.fetchone()[0]}")
