"""Daily diff report writer.

Writes `.pipeline/reports/YYYY-MM-DD.md` — appended to throughout the day,
one section per orchestrator run. Each section captures: scrape outcomes,
yields per board, shortlist hits, bypass alerts, and a brief tomorrow-focus.

The report is human-readable markdown intended for end-of-day skim.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PIPELINE_DIR = Path(__file__).resolve().parents[2] / ".pipeline"
REPORTS_DIR = PIPELINE_DIR / "reports"


def _today_path() -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return REPORTS_DIR / f"{stamp}.md"


def _utcnow() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def append_run_section(
    state: dict[str, Any],
    dispatch_results: dict[str, Any],
    upwork_passes: list[Any],
    ats_passes: list[Any],
    near_misses: list[Any] | None,
    bypass_alerts: list[str],
) -> Path:
    """Append a single run section to today's report. Returns the path."""
    path = _today_path()
    is_new = not path.exists()

    out: list[str] = []
    if is_new:
        out.append(f"# Orchestrator Report — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
        out.append("")
        out.append(
            "Auto-generated by `scripts/orchestrator/run.py`. One section per "
            "scheduled run (every 30 minutes). Sniper-mode posture: surface, "
            "do not act."
        )
        out.append("")
        out.append("---")
        out.append("")

    run_id = state.get("last_run_id", "?")
    out.append(f"## Run #{run_id} — {_utcnow()}")
    out.append("")

    # Scrape phase
    scrape_ok = dispatch_results.get("scrape_ok", False)
    scrape_msg = (dispatch_results.get("scrape_msg") or "").strip()
    out.append(f"**Scrape trigger:** {'OK' if scrape_ok else 'FAILED'}")
    if not scrape_ok and scrape_msg:
        out.append(f"  - error: `{scrape_msg[:200]}`")
    out.append("")

    # Per-board yields
    out.append("**Yields per board:**")
    out.append("")
    out.append("| Board | This run | EMA baseline | Status |")
    out.append("|---|---|---|---|")
    boards = dispatch_results.get("boards", {})
    for name in ("upwork_email", "greenhouse", "ashby", "lever"):
        bd = boards.get(name, {})
        jobs = bd.get("jobs", [])
        err = bd.get("error")
        baseline = state.get("boards", {}).get(name, {}).get("baseline_yield")
        baseline_str = f"{baseline:.1f}" if baseline is not None else "—"
        status = f"err: {err}" if err else "ok"
        out.append(f"| {name} | {len(jobs)} | {baseline_str} | {status} |")
    out.append("")

    # Filter outcomes
    out.append(f"**Hyper-selective filter results:**")
    out.append("")
    out.append(f"- Upwork passes: **{len(upwork_passes)}**")
    out.append(f"- ATS passes: **{len(ats_passes)}**")
    out.append(f"- Near misses (≥80, did not pass): {len(near_misses or [])}")
    out.append("")

    if upwork_passes or ats_passes:
        out.append("**Surfaced this run:**")
        out.append("")
        for r in upwork_passes[:5]:
            t = r.job.get("title", "?")[:70]
            url = r.job.get("url", "")
            out.append(f"- [Upwork {r.composite:.0f}] {t}")
            if url:
                out.append(f"  - {url}")
        for r in ats_passes[:5]:
            c = r.job.get("company", "?")
            t = r.job.get("title", "?")[:60]
            url = r.job.get("url", "")
            out.append(f"- [ATS {r.composite:.0f}] {c} — {t}")
            if url:
                out.append(f"  - {url}")
        out.append("")
    else:
        out.append("_No jobs surfaced. Hyper-selective filter held the line — this is normal._")
        out.append("")

    # Bypass alerts
    if bypass_alerts:
        out.append("**⚠️ Bypass alerts:**")
        out.append("")
        for alert in bypass_alerts:
            out.append(f"- {alert}")
        out.append("")

    # Connects
    connects = state.get("upwork", {}).get("connects_remaining", "?")
    out.append(f"**Upwork connects remaining:** {connects}")
    out.append("")
    out.append("---")
    out.append("")

    with path.open("a", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    return path


if __name__ == "__main__":
    # Smoke test
    fake_state = {"last_run_id": 0, "upwork": {"connects_remaining": 18}, "boards": {}}
    fake_dispatch = {
        "scrape_ok": True,
        "scrape_msg": "smoke test",
        "boards": {
            "upwork_email": {"jobs": [], "error": None},
            "greenhouse": {"jobs": [], "error": None},
            "ashby": {"jobs": [], "error": None},
            "lever": {"jobs": [], "error": None},
        },
    }
    p = append_run_section(fake_state, fake_dispatch, [], [], [], [])
    print(f"Wrote smoke section to {p}")
